/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.RefCarState;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-04T12:34:26.681Z[GMT]")
@Api(value = "ref_car_state", description = "the ref_car_state API")
public interface RefCarStateApi {

    @ApiOperation(value = "Получение данных о состоянии автомобиля", nickname = "refCarStateGet", notes = "", response = RefCarState.class, responseContainer = "List", tags={ "ref_car_state", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Операция успешно завершена.", response = RefCarState.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Неверное id состояни автомобиля.") })
    @RequestMapping(value = "/ref_car_state",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<RefCarState>> refCarStateGet(@ApiParam(value = "id для поиска.") @Valid @RequestParam(value = "id", required = false) Integer id);

}
