/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.controller;

import io.swagger.model.RefRole;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-04T12:34:26.681Z[GMT]")
@Api(value = "ref_role", description = "the ref_role API")
public interface RefRoleApi {

    @ApiOperation(value = "Получение данных о роли по идентификатору", nickname = "refRoleGet", notes = "", response = RefRole.class, responseContainer = "List", tags={ "ref_role", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Операция успешно завершена.", response = RefRole.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Неверное id роли.") })
    @RequestMapping(value = "/ref_role",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<RefRole>> refRoleGet( @ApiParam(value = "id для поиска.") @Valid @RequestParam(value = "id", required = false) Integer id);

}
